#import <UIKit/UIKit.h>
#include "dart_harness.h"
#include "flutter_hotpatch_updater.h"

/* Ed25519 public key (hex) — generated by keygen.py, matches private_key.pem used in 4-B */
static const char* kPatchPublicKeyHex =
    "9d2550fb40571238ee6bd8459ffa60bb2c121249abf44bebe0c1218faec9e82f";

/* App build fingerprint — must match target_build_fingerprint in patch bundle */
static const char* kBuildFingerprint = "1.0+1";

@interface ViewController : UIViewController
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.systemBackgroundColor;

    /* App data directory for Updater state persistence */
    NSArray *dataPaths = NSSearchPathForDirectoriesInDomains(
        NSApplicationSupportDirectory, NSUserDomainMask, YES);
    NSString *dataDir = [[dataPaths firstObject]
        stringByAppendingPathComponent:@"HotPatchUpdater"];
    [[NSFileManager defaultManager] createDirectoryAtPath:dataDir
        withIntermediateDirectories:YES attributes:nil error:nil];

    /* Initialize Updater (runs boot-loop watchdog internally) */
    int initResult = fhp_init([dataDir UTF8String], kBuildFingerprint);
    NSLog(@"[4D] fhp_init: %d", initResult);

    /* Check if a patch bundle is already staged for next boot.
       If not, stage the bundled patch from the app bundle (simulates downloaded patch). */
    const char* nextBootDir = fhp_get_next_boot_patch_dir();
    if (!nextBootDir) {
        /* Find patch_bundle/ inside app bundle */
        NSString *bundlePatchDir = [[NSBundle mainBundle]
            pathForResource:@"manifest" ofType:@"json" inDirectory:@"patch_bundle"];
        if (bundlePatchDir) {
            bundlePatchDir = [bundlePatchDir stringByDeletingLastPathComponent];
        } else {
            /* Fallback: patch_bundle is a directory at bundle root */
            bundlePatchDir = [[[NSBundle mainBundle] bundlePath]
                stringByAppendingPathComponent:@"patch_bundle"];
        }

        if ([[NSFileManager defaultManager] fileExistsAtPath:bundlePatchDir]) {
            NSLog(@"[4D] staging patch from: %@", bundlePatchDir);
            int stageResult = fhp_stage_patch([bundlePatchDir UTF8String], kPatchPublicKeyHex);
            NSLog(@"[4D] fhp_stage_patch: %d", stageResult);
            nextBootDir = fhp_get_next_boot_patch_dir();
        } else {
            NSLog(@"[4D] no patch_bundle found in app bundle — pure baseline");
        }
    }

    NSLog(@"[4D] next_boot_patch_dir: %s", nextBootDir ? nextBootDir : "(null = baseline)");

    /* Run Dart VM: patch path or NULL for baseline */
    const char *cResult = dart_run(nextBootDir);
    NSLog(@"[4D] Dart result: %s", cResult);

    /* Confirm App health to Updater (boot-loop watchdog clears pending state) */
    fhp_confirm_health();
    NSLog(@"[4D] confirmed health");

    /* Show result */
    NSString *result = [NSString stringWithUTF8String:cResult ? cResult : "ERROR"];
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectInset(self.view.bounds, 20, 0)];
    label.text = result;
    label.font = [UIFont systemFontOfSize:28 weight:UIFontWeightMedium];
    label.textAlignment = NSTextAlignmentCenter;
    label.numberOfLines = 0;
    label.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    [self.view addSubview:label];

    /* Write result for devicectl retrieval */
    NSArray *docPaths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *docDir = [docPaths firstObject];
    NSString *diagContent = [NSString stringWithFormat:
        @"result=%s\nnext_boot=%s\nbuild_fp=%s",
        cResult ? cResult : "nil",
        nextBootDir ? nextBootDir : "(nil=baseline)",
        kBuildFingerprint];
    [diagContent writeToFile:[docDir stringByAppendingPathComponent:@"result.txt"]
        atomically:YES encoding:NSUTF8StringEncoding error:nil];

    /* Free Updater-allocated string */
    if (nextBootDir) fhp_free_string(nextBootDir);
}

@end
