// GENERATED by gen.py — V10 perf, shape=arith. Interpreted kernel.
// Body is byte-identical to the host AOT kernel of the same case.
library;

@pragma('dyn-module:entry-point')
int kernel() {
  const seed = 42;
  var acc = seed;
  for (var i = 0; i < 100000; i++) {
    acc = acc * 1103515245 + 12345;
    acc = acc ^ (acc >> 7);
    acc = acc & 0x7fffffff;
  }
  return acc;
}
