// GENERATED by gen.py — V10 perf, shape=strbuild. Interpreted kernel.
// Body is byte-identical to the host AOT kernel of the same case.
library;

@pragma('dyn-module:entry-point')
int kernel() {
  const seed = 42;
  var acc = seed;
  for (var i = 0; i < 0; i++) {
    final s = '${acc & 255}';
    acc = acc + int.parse(s);
    acc = acc & 0x7fffffff;
  }
  return acc;
}
