// GENERATED by gen.py — V10 perf, shape=nativeheavy. Interpreted kernel.
// Body is byte-identical to the host AOT kernel of the same case.
library;

@pragma('dyn-module:entry-point')
int kernel() {
  const seed = 42;
  var acc = seed;
  for (var i = 0; i < 2000; i++) {
    final s = 'ab' * (64 + (acc & 1));
    acc = (acc + s.length) & 0x7fffffff;
  }
  return acc;
}
