#!/usr/bin/env python3
"""V10 perf spike code generator (multi-shape).

Emits `host/main.dart` and one `patch/cN.dart` per case, guaranteeing each AOT
baseline kernel and its interpreted-bytecode twin are byte-identical Dart source
(only the seed source differs: AOT takes a runtime seed to defeat constant-
folding; bytecode bakes a literal seed — dart2bytecode does no folding).

Measures k (interpret-vs-AOT slowdown) across function SHAPES, to bound the
range V10 needs:
  - arith    : pure integer arithmetic — the interpreter's WORST case (every
               unit of work is a bytecode dispatch). This is the k ceiling.
  - strbuild : allocate + interpolate a string each iter — the heavy work
               (alloc, format, GC) runs in the native VM runtime EVEN on the
               interpreted path, so the interpreter only dispatches the glue.
  - listalloc: allocate a small list each iter — same story, allocation-bound.
The strbuild/listalloc "effective k" is the realistic number; arith is the ceiling.

Cases are positional: host case i uses aotKernel<i>, and the bytecode paths are
passed to the host in cases.txt order — no name matching.

生成器保证每个 AOT 核函数与其解释字节码孪生逐字节相同。测三种形态的 k：纯算术是解释器
最坏情况(上界);字符串构建/列表分配的重活(分配/拼接/GC)在解释路径里仍走原生运行时,
只 dispatch 外围字节码,有效 k 应低得多——这才是真实补丁的典型值。
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Per-shape kernel body. `W` is baked as a literal loop bound; `seed` is the
# entry value. Every operator/method here is also exercised by the host's own
# AOT copy of the same kernel, so the bytecode patch references only host-
# retained symbols (closed-world tree-shake — see gate1-vm-spike skill §6).
def kernel_body(shape, w):
    if shape == 'arith':
        inner = (
            "    acc = acc * 1103515245 + 12345;\n"
            "    acc = acc ^ (acc >> 7);\n"
            "    acc = acc & 0x7fffffff;\n"
        )
    elif shape == 'strbuild':
        # Allocate + interpolate a numeric string, then int.parse it back each
        # iter. Interpolation + parse are REAL calls into native VM runtime
        # (identical on both paths); the heavy work runs native even when
        # interpreted. NB: avoid .length/[]/etc — those intrinsify in AOT so no
        # callable Function survives for the bytecode reader (closed-world tree-
        # shake, gate1-vm-spike skill §6). Interpolation + int.parse do survive
        # (non-intrinsified, host-exercised).
        inner = (
            "    final s = '${acc & 255}';\n"
            "    acc = acc + int.parse(s);\n"
            "    acc = acc & 0x7fffffff;\n"
        )
    elif shape == 'nativeheavy':
        # ONE heavy native call per iter: String.* allocates ~130 chars, then
        # .length. Count depends on runtime acc so AOT can't constant-fold the
        # allocation away (both paths do the real native work). Shows k → ~1 as
        # a single native call's work dwarfs the interpreter's per-iter dispatch.
        inner = (
            "    final s = 'ab' * (64 + (acc & 1));\n"
            "    acc = (acc + s.length) & 0x7fffffff;\n"
        )
    else:
        raise ValueError(shape)
    return (
        "  var acc = seed;\n"
        f"  for (var i = 0; i < {w}; i++) {{\n"
        f"{inner}"
        "  }\n"
        "  return acc;\n"
    )

# (shape, work_per_call, outer_calls). W=0 rows isolate per-call overhead (same
# invoke path for every shape); the large-W row gives that shape's per-iter cost.
CASES = [
    ('arith',      0,       5_000_000),
    ('arith',      100_000,     5_000),
    ('strbuild',   0,       2_000_000),
    ('strbuild',   2_000,      30_000),
    ('nativeheavy', 0,      2_000_000),
    ('nativeheavy', 2_000,     30_000),
]

def gen_patch(shape, w):
    return (
        f"// GENERATED by gen.py — V10 perf, shape={shape}. Interpreted kernel.\n"
        "// Body is byte-identical to the host AOT kernel of the same case.\n"
        "library;\n\n"
        "@pragma('dyn-module:entry-point')\n"
        "int kernel() {\n"
        "  const seed = 42;\n"
        f"{kernel_body(shape, w)}"
        "}\n"
    )

def gen_host():
    L = []
    L.append("// GENERATED by gen.py — V10 perf harness (host, multi-shape).\n")
    L.append("//\n")
    L.append("// Times AOT native vs interpreted-bytecode calls of byte-identical kernels\n")
    L.append("// across shapes (arith / strbuild / listalloc) to extract k per shape.\n")
    L.append("// Directly invokes both paths — no call-site rewrite (redirection already\n")
    L.append("// proven by Gate 1 V1-V5); this isolates raw interpreter cost.\n")
    L.append("library;\n\n")
    L.append("import 'dart:io';\n")
    L.append("import 'dart:_internal' as internal;\n\n")

    for i, (shape, w, _n) in enumerate(CASES):
        L.append(f"@pragma('vm:never-inline')\n")
        L.append(f"int aotKernel{i}(int seed) {{  // shape={shape} W={w}\n")
        L.append(kernel_body(shape, w))
        L.append("}\n\n")

    L.append("int Function(int) aotFor(int i) {\n")
    L.append("  switch (i) {\n")
    for i, _c in enumerate(CASES):
        L.append(f"    case {i}: return aotKernel{i};\n")
    L.append("    default: throw StateError('no aot kernel #\\$i');\n")
    L.append("  }\n")
    L.append("}\n\n")

    L.append("const shapes = <String>[\n")
    for (shape, _w, _n) in CASES:
        L.append(f"  '{shape}',\n")
    L.append("];\n")
    L.append("const works = <int>[\n")
    for (_shape, w, _n) in CASES:
        L.append(f"  {w},\n")
    L.append("];\n")
    L.append("const calls = <int>[\n")
    for (_shape, _w, n) in CASES:
        L.append(f"  {n},\n")
    L.append("];\n\n")

    L.append(r"""
void main(List<String> args) {
  if (args.length != shapes.length) {
    stderr.writeln('expected ${shapes.length} bytecode paths, got ${args.length}');
    exit(2);
  }
  final closures = <Object>[];
  for (var c = 0; c < shapes.length; c++) {
    final bytes = File(args[c]).readAsBytesSync();
    final closure = internal.loadDynamicModuleClosure(bytes: bytes);
    if (closure == null || closure is! Function) {
      stderr.writeln('load failed for ${args[c]}: $closure');
      exit(3);
    }
    closures.add(closure);
  }

  // Warm both paths to steady state.
  for (var c = 0; c < shapes.length; c++) {
    final aot = aotFor(c);
    var s = 1;
    for (var i = 0; i < 500; i++) s = aot(s) | 1;
    for (var i = 0; i < 500; i++) internal.invokeDynamicModuleClosure(closures[c]);
  }

  stdout.writeln('shape\tW\tN\tnative_ns/call\tinterp_ns/call\tk(call)\tnat_ns/iter\tint_ns/iter\tk_iter');
  // Collect per-shape rows to compute per-iter slope (overhead cancels).
  final byShape = <String, Map<int, List<double>>>{}; // shape -> W -> [natPerCall, intPerCall]
  for (var c = 0; c < shapes.length; c++) {
    final shape = shapes[c], w = works[c], n = calls[c];
    final aot = aotFor(c);
    final closure = closures[c];

    var acc = 7;
    final swN = Stopwatch()..start();
    for (var i = 0; i < n; i++) acc = aot(acc);
    swN.stop();
    if (acc == 0x12345678) stdout.write('');

    var sink = 0;
    final swI = Stopwatch()..start();
    for (var i = 0; i < n; i++) {
      sink ^= internal.invokeDynamicModuleClosure(closure) as int;
    }
    swI.stop();
    if (sink == 0x12345678) stdout.write('');

    final natPerCall = swN.elapsedMicroseconds * 1000.0 / n;
    final intPerCall = swI.elapsedMicroseconds * 1000.0 / n;
    final kCall = intPerCall / natPerCall;
    final natIter = w == 0 ? double.nan : natPerCall / w;
    final intIter = w == 0 ? double.nan : intPerCall / w;
    final kIter = w == 0 ? double.nan : intIter / natIter;
    byShape.putIfAbsent(shape, () => {})[w] = [natPerCall, intPerCall];
    stdout.writeln('$shape\t$w\t$n\t${natPerCall.toStringAsFixed(2)}\t'
        '${intPerCall.toStringAsFixed(2)}\t${kCall.toStringAsFixed(1)}\t'
        '${natIter.isNaN ? "-" : natIter.toStringAsFixed(3)}\t'
        '${intIter.isNaN ? "-" : intIter.toStringAsFixed(3)}\t'
        '${kIter.isNaN ? "-" : kIter.toStringAsFixed(1)}');
  }

  stdout.writeln('---');
  // Per-shape effective k from slope: (big - W0) cancels per-call overhead.
  for (final shape in byShape.keys) {
    final m = byShape[shape]!;
    final ws = m.keys.toList()..sort();
    if (ws.length < 2 || ws.first != 0) continue;
    final w0 = m[0]!, big = m[ws.last]!;
    final natSlope = (big[0] - w0[0]) / ws.last;
    final intSlope = (big[1] - w0[1]) / ws.last;
    stdout.writeln('$shape: per-iter native=${natSlope.toStringAsFixed(4)}ns '
        'interp=${intSlope.toStringAsFixed(4)}ns  '
        'effective k_work=${(intSlope / natSlope).toStringAsFixed(1)}x');
  }
  final ov = byShape.values.first[0]!;
  stdout.writeln('per-call overhead (W=0): native=${ov[0].toStringAsFixed(1)}ns '
      'interp=${ov[1].toStringAsFixed(1)}ns ratio=${(ov[1] / ov[0]).toStringAsFixed(1)}x');
}
""")
    return ''.join(L)

def main():
    os.makedirs(os.path.join(HERE, 'host'), exist_ok=True)
    os.makedirs(os.path.join(HERE, 'patch'), exist_ok=True)
    with open(os.path.join(HERE, 'host', 'main.dart'), 'w', newline='\n') as f:
        f.write(gen_host())
    for i, (shape, w, _n) in enumerate(CASES):
        with open(os.path.join(HERE, 'patch', f'c{i}.dart'), 'w', newline='\n') as f:
            f.write(gen_patch(shape, w))
    with open(os.path.join(HERE, 'cases.txt'), 'w', newline='\n') as f:
        f.write('\n'.join(str(i) for i, _c in enumerate(CASES)) + '\n')
    print(f'generated host/main.dart + {len(CASES)} patch files + cases.txt')

if __name__ == '__main__':
    main()
