// GENERATED by gen_sample.py — app entry.
library;

import 'dart:io';
import 'mod0.dart' as m0;
import 'mod1.dart' as m1;
import 'mod2.dart' as m2;
import 'mod3.dart' as m3;
import 'mod4.dart' as m4;
import 'mod5.dart' as m5;
import 'mod6.dart' as m6;
import 'mod7.dart' as m7;

void main(List<String> args) {
  final i = args.length + 3;
  final total = m0.moduleChecksum(i) + m1.moduleChecksum(i) + m2.moduleChecksum(i) + m3.moduleChecksum(i) + m4.moduleChecksum(i) + m5.moduleChecksum(i) + m6.moduleChecksum(i) + m7.moduleChecksum(i);
  stdout.writeln(total);
}
