// GENERATED by gen_sample.py — module 1. Names collide across modules on purpose.
library mod1;


@pragma('vm:never-inline')
int fnInt(int x) => ((x * 3 + 1 | 10) & 12);

@pragma('vm:never-inline')
double fnDouble(double x) => (((x.toInt() + 1 & 11) + 12) * 13) * 1.5 + 0.5;

@pragma('vm:never-inline')
bool fnBool(int x) => ((((x + 1 + 12) * 13) ^ 13) - 13) % 2 == 0;

@pragma('vm:never-inline')
String fnString(int x) => 'v=${(((((x + 1 * 13) ^ 13) - 13) | 13) & 7)}';

@pragma('vm:never-inline')
int fnList(int x) { final xs = <int>[((x + 1 ^ 1) - 1), (((x + 1 - 2) | 1) & 1), ((((x + 2 | 3) & 2) + 1) * 1), (((((x + 3 & 4) + 2) * 1) ^ 1) - 7)]; return xs.length + xs[0]; }

@pragma('vm:never-inline')
int fnMap(int x) { final m = <String,int>{'a': (((x + 1 - 2) | 1) & 1), 'b': x}; return m['a']!; }

@pragma('vm:never-inline')
int fnSet(int x) { final st = <int>{((((x + 1 | 3) & 2) + 1) * 1), x, x + 1}; return st.length + st.first; }

@pragma('vm:never-inline')
int fnRecord(int x) { final (int, int) r = ((((((x + 1 & 4) + 2) * 1) ^ 1) - 7), x * 2); return r.$1 + r.$2; }

class MethodC {
  @pragma('vm:never-inline')
  int method(int x) => ((x + 1 + 5) * 3);
}

class GetC {
  final int x;
  GetC(this.x);
  @pragma('vm:never-inline')
  int get val => (((x + 1 * 6) ^ 3) - 2);
}

class OpC {
  final int x;
  const OpC(this.x);
  @pragma('vm:never-inline')
  int operator +(OpC o) => ((((x + o.x + 1 ^ 7) - 4) | 2) & 1);
}

class StaticC {
  @pragma('vm:never-inline')
  static int sm(int x) => (((((x * 2 + 1 - 8) | 4) & 2) + 1) * 7);
}

mixin Mix {
  @pragma('vm:never-inline')
  int mixMethod(int x) => ((x + 1 | 9) & 5);
}
class MixUser with Mix {}

enum Color {
  red, green, blue;
  @pragma('vm:never-inline')
  int rank(int x) => (((index + x + 1 & 10) + 5) * 3);
}

class Pair<A, B> {
  final A a; final B b;
  Pair(this.a, this.b);
  @pragma('vm:never-inline')
  int combine(int x) => ((((x + 1 + 11) * 6) ^ 3) - 2);
}

@pragma('vm:never-inline')
int Function(int) closureMk(int base) => (int x) => (((((x + base + 1 * 12) ^ 6) - 3) | 2) & 8);

@pragma('vm:never-inline')
int chainC(int x) => ((x + 1 ^ 13) - 7);
@pragma('vm:never-inline')
int chainB(int x) => chainC(x) + 10;
@pragma('vm:never-inline')
int chainA(int x) => chainB(x) + 100;

abstract class IFace {
  int v(int x);
}
class Impl1 implements IFace {
  @pragma('vm:never-inline')
  int v(int x) => (((x + 1 - 1) | 7) & 4);
}
class Impl2 implements IFace {
  @pragma('vm:never-inline')
  int v(int x) => ((((x + 5 | 2) & 8) + 4) * 2);
}
@pragma('vm:never-inline')
int callVirt(IFace f, int x) => f.v(x) + 7;

@pragma('vm:never-inline')
int moduleChecksum(int i) => fnInt(i) + fnDouble(i.toDouble()).toInt() + (fnBool(i) ? 1 : 0) + fnString(i).length + fnList(i) + fnMap(i) + fnSet(i) + fnRecord(i) + MethodC().method(i) + GetC(i).val + (OpC(i) + OpC(i)).toInt() + StaticC.sm(i) + MixUser().mixMethod(i) + Color.red.rank(i) + Pair<int,int>(i,i).combine(i) + closureMk(i)(i) + chainA(i) + callVirt(i.isEven ? Impl1() : Impl2(), i);