// GENERATED by gen.py — V10 perf harness (host, multi-shape).
//
// Times AOT native vs interpreted-bytecode calls of byte-identical kernels
// across shapes (arith / strbuild / listalloc) to extract k per shape.
// Directly invokes both paths — no call-site rewrite (redirection already
// proven by Gate 1 V1-V5); this isolates raw interpreter cost.
library;

import 'dart:io';
import 'dart:_internal' as internal;

@pragma('vm:never-inline')
int aotKernel0(int seed) {  // shape=arith W=0
  var acc = seed;
  for (var i = 0; i < 0; i++) {
    acc = acc * 1103515245 + 12345;
    acc = acc ^ (acc >> 7);
    acc = acc & 0x7fffffff;
  }
  return acc;
}

@pragma('vm:never-inline')
int aotKernel1(int seed) {  // shape=arith W=100000
  var acc = seed;
  for (var i = 0; i < 100000; i++) {
    acc = acc * 1103515245 + 12345;
    acc = acc ^ (acc >> 7);
    acc = acc & 0x7fffffff;
  }
  return acc;
}

@pragma('vm:never-inline')
int aotKernel2(int seed) {  // shape=strbuild W=0
  var acc = seed;
  for (var i = 0; i < 0; i++) {
    final s = '${acc & 255}';
    acc = acc + int.parse(s);
    acc = acc & 0x7fffffff;
  }
  return acc;
}

@pragma('vm:never-inline')
int aotKernel3(int seed) {  // shape=strbuild W=2000
  var acc = seed;
  for (var i = 0; i < 2000; i++) {
    final s = '${acc & 255}';
    acc = acc + int.parse(s);
    acc = acc & 0x7fffffff;
  }
  return acc;
}

@pragma('vm:never-inline')
int aotKernel4(int seed) {  // shape=nativeheavy W=0
  var acc = seed;
  for (var i = 0; i < 0; i++) {
    final s = 'ab' * (64 + (acc & 1));
    acc = (acc + s.length) & 0x7fffffff;
  }
  return acc;
}

@pragma('vm:never-inline')
int aotKernel5(int seed) {  // shape=nativeheavy W=2000
  var acc = seed;
  for (var i = 0; i < 2000; i++) {
    final s = 'ab' * (64 + (acc & 1));
    acc = (acc + s.length) & 0x7fffffff;
  }
  return acc;
}

int Function(int) aotFor(int i) {
  switch (i) {
    case 0: return aotKernel0;
    case 1: return aotKernel1;
    case 2: return aotKernel2;
    case 3: return aotKernel3;
    case 4: return aotKernel4;
    case 5: return aotKernel5;
    default: throw StateError('no aot kernel #\$i');
  }
}

const shapes = <String>[
  'arith',
  'arith',
  'strbuild',
  'strbuild',
  'nativeheavy',
  'nativeheavy',
];
const works = <int>[
  0,
  100000,
  0,
  2000,
  0,
  2000,
];
const calls = <int>[
  5000000,
  5000,
  2000000,
  30000,
  2000000,
  30000,
];


void main(List<String> args) {
  if (args.length != shapes.length) {
    stderr.writeln('expected ${shapes.length} bytecode paths, got ${args.length}');
    exit(2);
  }
  final closures = <Object>[];
  for (var c = 0; c < shapes.length; c++) {
    final bytes = File(args[c]).readAsBytesSync();
    final closure = internal.loadDynamicModuleClosure(bytes: bytes);
    if (closure == null || closure is! Function) {
      stderr.writeln('load failed for ${args[c]}: $closure');
      exit(3);
    }
    closures.add(closure);
  }

  // Warm both paths to steady state.
  for (var c = 0; c < shapes.length; c++) {
    final aot = aotFor(c);
    var s = 1;
    for (var i = 0; i < 500; i++) s = aot(s) | 1;
    for (var i = 0; i < 500; i++) internal.invokeDynamicModuleClosure(closures[c]);
  }

  stdout.writeln('shape\tW\tN\tnative_ns/call\tinterp_ns/call\tk(call)\tnat_ns/iter\tint_ns/iter\tk_iter');
  // Collect per-shape rows to compute per-iter slope (overhead cancels).
  final byShape = <String, Map<int, List<double>>>{}; // shape -> W -> [natPerCall, intPerCall]
  for (var c = 0; c < shapes.length; c++) {
    final shape = shapes[c], w = works[c], n = calls[c];
    final aot = aotFor(c);
    final closure = closures[c];

    var acc = 7;
    final swN = Stopwatch()..start();
    for (var i = 0; i < n; i++) acc = aot(acc);
    swN.stop();
    if (acc == 0x12345678) stdout.write('');

    var sink = 0;
    final swI = Stopwatch()..start();
    for (var i = 0; i < n; i++) {
      sink ^= internal.invokeDynamicModuleClosure(closure) as int;
    }
    swI.stop();
    if (sink == 0x12345678) stdout.write('');

    final natPerCall = swN.elapsedMicroseconds * 1000.0 / n;
    final intPerCall = swI.elapsedMicroseconds * 1000.0 / n;
    final kCall = intPerCall / natPerCall;
    final natIter = w == 0 ? double.nan : natPerCall / w;
    final intIter = w == 0 ? double.nan : intPerCall / w;
    final kIter = w == 0 ? double.nan : intIter / natIter;
    byShape.putIfAbsent(shape, () => {})[w] = [natPerCall, intPerCall];
    stdout.writeln('$shape\t$w\t$n\t${natPerCall.toStringAsFixed(2)}\t'
        '${intPerCall.toStringAsFixed(2)}\t${kCall.toStringAsFixed(1)}\t'
        '${natIter.isNaN ? "-" : natIter.toStringAsFixed(3)}\t'
        '${intIter.isNaN ? "-" : intIter.toStringAsFixed(3)}\t'
        '${kIter.isNaN ? "-" : kIter.toStringAsFixed(1)}');
  }

  stdout.writeln('---');
  // Per-shape effective k from slope: (big - W0) cancels per-call overhead.
  for (final shape in byShape.keys) {
    final m = byShape[shape]!;
    final ws = m.keys.toList()..sort();
    if (ws.length < 2 || ws.first != 0) continue;
    final w0 = m[0]!, big = m[ws.last]!;
    final natSlope = (big[0] - w0[0]) / ws.last;
    final intSlope = (big[1] - w0[1]) / ws.last;
    stdout.writeln('$shape: per-iter native=${natSlope.toStringAsFixed(4)}ns '
        'interp=${intSlope.toStringAsFixed(4)}ns  '
        'effective k_work=${(intSlope / natSlope).toStringAsFixed(1)}x');
  }
  final ov = byShape.values.first[0]!;
  stdout.writeln('per-call overhead (W=0): native=${ov[0].toStringAsFixed(1)}ns '
      'interp=${ov[1].toStringAsFixed(1)}ns ratio=${(ov[1] / ov[0]).toStringAsFixed(1)}x');
}
