#!/usr/bin/env python3
"""
Generate dynamic_interface.yaml to preserve symbols for hotpatch access.
Analyzes patch source files to find what symbols they reference,
then generates the YAML to preserve those in the baseline build.

Usage:
  python3 gen_dynamic_interface.py \
    --patches patches/*.dart \
    --output dynamic_interface.yaml
"""
import argparse, os, re

COMMON_PRESERVED = [
    # Dart core commonly needed by patches
    'dart:core::String',
    'dart:core::int',
    'dart:core::double',
    'dart:core::List',
    'dart:core::Map',
    'dart:core::print',
    'dart:core::StringBuffer',
    'dart:_internal::redirectClosureEntryPoint',
]

def extract_imports(dart_src):
    """Extract package imports from Dart source."""
    return re.findall(r"import '(package:[^']+)'", dart_src)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--patches', nargs='+', default=[])
    p.add_argument('--output', default='dynamic_interface.yaml')
    args = p.parse_args()

    callable_entries = list(COMMON_PRESERVED)

    for patch_file in args.patches:
        if not os.path.exists(patch_file):
            continue
        src = open(patch_file).read()
        imports = extract_imports(src)
        for imp in imports:
            # Add the full package API surface
            pkg = imp.split('/')[0].replace('package:', '')
            callable_entries.append(f'# from {imp}')

    yaml_content = """# dynamic_interface.yaml — generated by gen_dynamic_interface.py
# Lists symbols that MUST be preserved in baseline AOT build for hotpatch access.
# Add this file to your gen_kernel invocation:
#   gen_kernel --dynamic-interface dynamic_interface.yaml ...

callable:
"""
    for entry in callable_entries:
        if entry.startswith('#'):
            yaml_content += f"  {entry}\n"
        else:
            yaml_content += f"  - {entry}\n"

    open(args.output, 'w').write(yaml_content)
    print(f"Generated: {args.output}")

if __name__ == '__main__':
    main()

