#!/usr/bin/env python3
"""
Generate a dispatcher patch.dart from multiple function implementations.
Allows bundling multiple function patches into one .dill entry-point.

CONSTRAINT: dart2bytecode requires the entry-point to be a static no-argument
method. This generator uses a global-variable protocol:
  1. Host writes function name to _dispatchFn
  2. Host calls dispatch() (the single entry-point)
  3. Host reads result from _dispatchResult

Usage:
  python3 gen_dispatcher.py \
    --functions greet:patches/greet.dart format:patches/format.dart \
    --output /tmp/multi_patch.dart
"""
import argparse, os, re

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--functions', nargs='+', help='name:file pairs')
    p.add_argument('--output', required=True)
    p.add_argument('--library', default='hotpatch_patch')
    args = p.parse_args()

    impls = []
    cases = []

    for pair in (args.functions or []):
        fn_name, fn_file = pair.split(':', 1)
        content = open(fn_file).read()
        # Strip library declaration and dyn-module pragmas
        fn_body = re.sub(r"library\s+\S+;", "", content)
        fn_body = re.sub(r"@pragma\('dyn-module:entry-point'\)\s*", "", fn_body)
        # Rename to avoid name collisions with dispatch() scope
        fn_body = re.sub(
            rf'\b{re.escape(fn_name)}\s*\(',
            f'_patched_{fn_name}(',
            fn_body
        )
        impls.append(fn_body.strip())
        cases.append(f"    case '{fn_name}': _dispatchResult = _patched_{fn_name}().toString(); return;")

    dispatch_table = '\n'.join(cases)

    output = f"""library {args.library};

// Auto-generated dispatcher — DO NOT EDIT
// Generated by gen_dispatcher.py

// Shared state for no-arg dispatch protocol
String _dispatchFn = '';
String _dispatchResult = '';

// Implementations
{chr(10).join(impls)}

// Single no-argument entry-point (required by dart2bytecode constraint)
@pragma('dyn-module:entry-point')
void dispatch() {{
  final fn = _dispatchFn;
  switch (fn) {{
{dispatch_table}
    default: _dispatchResult = '{{"error":"unknown:$fn"}}';
  }}
}}
"""
    open(args.output, 'w').write(output)
    print(f"Generated: {args.output}")
    print(f"Functions: {[p.split(':')[0] for p in (args.functions or [])]}")

if __name__ == '__main__':
    main()
